### ISSUE TITLE
AUTHENTICATION: add Persona+LDAP login 

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-web#32]

**Comment by ckarlof** [comment]
Who will be allowed to log in? If it's going to be restricted to internal Mozilla employees, LDAP via okta or Persona would be a better fit so it's easy to revoke access later.

FxA is open to all, so if you want anyone to be able to login, then FxA is a fine choice.

**Comment by rpappalax** [comment]
It's a tool primarily for Cloud Services folks, so definitely restricted.  Sounds like Persona may be the best way to go for now.

**Comment by pdehaan** [comment]
+1 Persona.
@rpappalax and I will hack on this. Assigning to rpapa so this actually moves forward.

**Comment by pdehaan** [comment]
OK, i found another solution which *may* work, or may confuse things slightly as we're trying to do Hapi+Angular SPA:

1. [**hapi-passport**](https://www.npmjs.com/package/hapi-passport) &mdash; Passport Strategy connector to hapi.
2. [**passport-persona**](https://www.npmjs.com/package/passport-persona) &mdash; Mozilla Persona authentication strategy for Passport.

I'll try and hack around with this and see if it is compatible w/ Hapi 8.x and I can get anywhere.

**Comment by pdehaan** [comment]
![](https://dl.dropboxusercontent.com/u/4509565/lols/isuckatsecurity.jpg)

**Comment by rpappalax** [comment]
copypasta - from here:
https://github.com/pdehaan/hapi-persona/blob/master/server/routes/auth.js
to
https://github.com/loads/loads-web/blob/master/server/controllers/login.js#L12
