### ISSUE TITLE
REPORTS: Annotations

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-web#33]
Porting over some notes from other repo....

In talking with ops, it occurred to me that being able to annotate runs would be really useful. 
We could store annotations by run_id and have them display in the detail view (below the run data).
Also, any user could come in later and do an annotation after the fact. Ideally, each annotation would include input username & datetime stamp.

Probably doesn't make sense to push this data back to the loads database, so we could cache it locally.

hence, there would probably be server side values for:
user_id
created_at
and a client side value(s) for:
annotation_user_id
annotation_created_at
annotation_updated_at

**Comment by rpappalax** [comment]
porting over more notes from pdehaan:

I think a workable flow would be something like:

1. authenticated user (you must be authenticated to browse/use the site) finds an active/finished loads run and can leave an annotation/comment.

2. comments will just be a big text box (similar to this GitHub thing here), and support at least some level of Markdown (for images and links, etc). I'm quite the fan of https://www.npmjs.org/package/remarkable at the moment. I'm guessing that we won't really need some "complex" tab-like UI for Write/Preview.

3. users should maybe be able to edit a message (all messages, or only their own?) Possibly add
    support for deleting comments. Should be trivial since comments will likely just be flat and not nested.

4. annotations/comments will be stored in the database as markdown, and will be converted to HTML on the server/client (but probably server). This means we'll need another /api/ endpoint that talks to our MySQL database to retrieve annotations via runId and display the user's ID, comment date, and comment text (as HTML).

The commenting needs to be at least as good as Bugzilla, which puts our bar for success fairly low. Ideally we'll be on par w/ GitHub commenting, minus roles like ("collaborator", and "owner") and an obvious lack of markdown comment preview.

**Comment by rpappalax** [comment]
more from pdehaan:
Support for Markdown with auto-linking of URLs and support for animated GIFs.
See https://www.npmjs.org/package/remarkable and/or https://www.npmjs.org/package/autolinker.

**Comment by pdehaan** [comment]
I can't remember if this is "done".
We have some crude commenting, but i haven't looked at it in a while.
I'm hesitant to close this currently since we want to replace MySQL with Dynamo or something else more interesting (although we do have a separate bug for that; see #57).

**Comment by rpappalax** [comment]
i'd like to get some data runs from loadsv2 loaded this week, then we can see how effective annotations are with real data.  last time i looked at what you'd put in place it looked really good, but we may want to take another pass it to be sure before we close this.

**Comment by pdehaan** [comment]
See #57

**Comment by chartjes** [comment]
wontfix
