### ISSUE TITLE
Add Pagination for Active and Finished Runs

### ISSUE THREAD

**Issue by darkwing** [loads/loads-web#40]

**Comment by pdehaan** [comment]
Not sure about getting archived results, but I did find this commit in the old repo where we got 30 results instead of 10. https://github.com/loads/loads-web/commit/3521e4806f527d00a174cad4d1f4600c797150c1

Not sure how we'd hack our JavaScript websocket code with the new `size` yet.

**Comment by rpappalax** [comment]
We can leave this one be for now, since we're using Loads, v1 to demo at the moment and Loads, v1 doesn't retain enough historical info to paginate.

**Comment by rpappalax** [comment]
I'll generate test data with loadsv2 on Mon.

**Comment by rpappalax** [comment]
There's about 25-30 test runs on loads-broker loaded now.  Let me know if you need more data to work on pagination.  From the loads-web server, you can query the data thusly: 
$ curl http://loadsv2.stage.mozaws.net:8080/api
Kit is going to add ability to 'limit' data ala:
$ curl http://loadsv2.stage.mozaws.net:8080/api?limit=10,31 or some such...
but for now, that call will return a DELUGE of all the records.  Should be good enough for us to work on this issue though.

**Comment by pdehaan** [comment]
(it's like @rpappalax is assigning and unassigning EVERYBODY!) #calmdownbro

---

We no longer know who kicked off the run? /cc @kitcambridge 

```js
{
  aborted: false,
  completed_at: "2015-03-07T00:16:30.888292",
  created_at: "2015-03-06T23:52:51.510171",
  id: 1,
  plan_id: 2,
  started_at: "2015-03-07T00:02:23.028523",
  state: 3,
  uuid: "50bc7739-5fe5-4523-904d-0a0924405506"
},
```

Also, can somebody give me a quick run down on the ID mapping for `state`, or point me to find the "M" that I can "RTF".

Question number the third, I assume that endpoint isn't a self-updating websocket (since I'm watching render HTML in my Internet Browser App). So the new plan is just to monitor it on a `setInterval()` type thing? (That's totally fine and cool, just wanted to confirm in my brain-space of what the flow should be in case that means I can rip the websocket guts out of the Angular app).

**Comment by darkwing** [comment]
Who are the questions steared toward?

**Comment by pdehaan** [comment]
@darkwing Everybody and nobody. (but mostly @kitcambridge, as i'm sure he knows what `state` ids mean, or what API doc explains it).

**Comment by pdehaan** [comment]
I RTFMed (http://loadsv2.readthedocs.org/en/latest/api/db.html#loadsbroker.db.status_to_text).

Status is documented here: [**loads/loads-broker** ./loadsbroker/db.py:66-83](https://github.com/loads/loads-broker/blob/3f65895ffa4f7e3d43e6c4e764af2722daed3151/loadsbroker/db.py#L66-L83):

```python
INITIALIZING = 0
RUNNING = 1
TERMINATING = 2
COMPLETED = 3


def status_to_text(status):
    """Converts status states to an output-friendly format"""
    if status == INITIALIZING:
        return "INITIALIZING"
    elif status == RUNNING:
        return "RUNNING"
    elif status == TERMINATING:
        return "TERMINATING"
    elif status == COMPLETED:
        return "COMPLETED"
    else:
        return "UNKNOWN"
```

I'm guessing we just keep our own map of status ID to friendly names (unless there is a way to grab them via the Python API), but superficially this seems as easy as us maintaining:

```js
function status_to_text(status) {
  var statuses = ['INITIALIZING', 'RUNNING', 'TERMINATING', 'COMPLETED'];
  return statuses[status] || 'UNKNOWN';
}
```

**Comment by pdehaan** [comment]
OK, not quite related to paged results, but this should convert the nested objects format of the http://loadsv2.stage.mozaws.net:8080/api results and make it a bit easier to display in Angular:

```js
var moment = require('moment');
var stringify = require('canonical-json');

var data = require('./loads-data.json');

console.log(stringify(explodeJson(data), null, 2));

// Filter an array and return only the object with a specific `id`.
function filterArrById(arr, id) {
  return arr.filter(function (item) {
    return (item.id === id);
  }).pop();
}

// Convert a status (number), into a human readable string.
function status_to_text(status) {
  var statuses = ['INITIALIZING', 'RUNNING', 'TERMINATING', 'COMPLETED'];
  return statuses[status] || 'UNKNOWN';
}

function explodeJson(data) {
  if (!data) {
    console.error('What\'s this garbage?');
    return {};
  }
  data.runs = data.runs.map(function (run) {
    // Convert date strings to date objects.
    ['created_at', 'started_at', 'completed_at'].forEach(function (field) {
      run[field] = new Date(run[field]);
    });
    var diff = run.completed_at - run.started_at;
    run.duration = moment.duration(diff).humanize();
    run.created = moment(run.created_at).fromNow();
    run.state = {
      id: run.state,
      text: status_to_text(run.state)
    };
    run.plan = filterArrById(data.plans, run.plan_id);
    // Delete duplicate key now that it can be accessed via `plan.id`.
    delete run.plan_id;
    return run;
  });
  data.plans = data.plans.map(function (plan) {
    plan.project = filterArrById(data.projects, plan.project_id);
    // Delete duplicate key now that it can be accessed via `project.id`.
    delete plan.project_id;
    return plan;
  });
  // Delete duplicate values now that they are merged into runs.
  delete data.plans;
  delete data.projects;
  return data;
}
```

And turn it into this magic:
```json
{
  "runs": [
    {
      "aborted": false,
      "completed_at": "2015-03-07T00:16:30.888Z",
      "created": "13 days ago",
      "created_at": "2015-03-06T23:52:51.510Z",
      "duration": "14 minutes",
      "id": 1,
      "plan": {
        "description": "Single PushGo server, 2 sets of testers for peak of 200k connections.",
        "enabled": false,
        "id": 2,
        "name": "Moar Servers",
        "project": {
          "home_page": null,
          "id": 1,
          "name": "Push Testing",
          "owner": null,
          "uuid": "{{ random uuid }}"
        },
        "uuid": "{{ random uuid }}"
      },
      "started_at": "2015-03-07T00:02:23.028Z",
      "state": {
        "id": 3,
        "text": "COMPLETED"
      },
      "uuid": "{{ random uuid }}"
    }, {
      "...."
    }
  ],
  "status": 200,
  "success": true,
  "version": "0.1"
}
```

Not sure how much of that is necessary, or if we only need a subset of the run/plan/project data. Maybe if we only need run information, this is all moot.

**Comment by pdehaan** [comment]
Filed upstream in **loads-broker** side as https://github.com/loads/loads-broker/issues/28

**Comment by chartjes** [comment]
wontfix
