### ISSUE TITLE
Update Active Table Item Styles

### ISSUE THREAD

**Issue by darkwing** [loads/loads-web#41]
As of this moment, elements displaying in the "active" column get "success styles applied;  that isn't necessarily true, so we should add a third state.

**Comment by darkwing** [comment]
This might not actually be needed -- green until it goes bad, because I'm seeing the error style while runs are still active, which actually is informative.

**Comment by pdehaan** [comment]
yeah, i wasn't sure what to do about that... it's maybe a bit misleading to show active as green, should be trivial enough to show the isActive as yellow while they are running. :shrug:

**Comment by rpappalax** [comment]
Loads, v1 uses yellow for active jobs, which we could also do.  At least it's understood by users of the tool and not too offensive.  Another option would be to borrow the Jenkins paradigm for this.  The obvious choices for historical are green=PASSED, red=FAILED (same as Loads, v1), but for active jobs they use blinking icon.  I know, it may not be pretty, but it's an option that would be understood.

**Comment by darkwing** [comment]
Meh, this isn't important anymore. :)
