### ISSUE TITLE
REPORTS: Annotations - Convert MySQL to DynamoDB?

### ISSUE THREAD

**Issue by pdehaan** [loads/loads-web#57]
Dynamo is cool, or whatever @darkwing prefers.

If we're nuking MySQL, we should also rip out the **sequelize** ORM library code too since I don't think that's supported outside of PostgreSQL, MySQL, MariaDB, SQLite and MSSQL.

**Comment by pdehaan** [comment]
Currently we're only using MySQL to store comments for the runs. 
- https://github.com/loads/loads-web/blob/master/server/db.js
- https://github.com/loads/loads-web/blob/master/server/routes/GET-comments.js
- https://github.com/loads/loads-web/blob/master/server/routes/POST-comments.js

**Comment by kitcambridge** [comment]
FWIW, the broker persists to SQLite (or Postgres) via [SQLAlchemy](http://www.sqlalchemy.org/), and [Grafana 2](http://grafana.org/blog/2015/02/10/Grafana-2-Alpha-and-preview.html) can save dashboards to any SQL-like database. It might make sense to use a single Postgres cluster on AWS...or not. Whatever is easiest for you. :smile_cat:

**Comment by rpappalax** [comment]
i can look into replacing heroku w/ RDS

**Comment by chartjes** [comment]
wontfix
