### ISSUE TITLE
Add AWS regions and EC2 instance types to front end project builder

### ISSUE THREAD

**Issue by pdehaan** [loads/loads-web#62]
Now that we have an [/api/aws](https://github.com/loads/loads-web/blob/master/server/routes/api.js#L5) route, we should see if we can dynamically load it in the front end app to display the [`instance_type`](https://github.com/loads/loads-web/blob/6b3a244e097ce34b8bb3628d5a3bb8a405889b89/client/static/assets/views/projects-builder.html#L60) and `instance_region` in the Project Builder as a <select> or <datalist>.

The **/api/aws** route should return a JSON barf with the following fields/values:

``` json
{
  "instanceTypes": [
    "t2.micro",
    "t2.small",
    "t2.medium",
    "m3.medium",
    "m3.large",
    "m3.xlarge",
    "m3.2xlarge",
    "c4.large",
    "c4.xlarge",
    "c4.2xlarge",
    "c4.4xlarge",
    "c4.8xlarge",
    "c3.large",
    "c3.xlarge",
    "c3.2xlarge",
    "c3.4xlarge",
    "c3.8xlarge"
  ],
  "regions": {
    "ap-northeast-1": "Asia Pacific (Tokyo)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
    "ap-southeast-2": "Asia Pacific (Sydney)",
    "eu-central-1": "EU (Frankfurt)",
    "eu-west-1": "EU (Ireland)",
    "sa-east-1": "South America (Sao Paulo)",
    "us-east-1": "US East (N. Virginia)",
    "us-west-1": "US West (N. California)",
    "us-west-2": "US West (Oregon)"
  }
}
```

We could either load those async via jQuery's `$.get()`, or maybe see if we turn it into an Angular `factory` or `service` so we can use templating and loops instead of direct DOM hackery.

**Comment by pdehaan** [comment]
@darkwing I think this is just some AJAX loading and injecting into your form. Or maybe some deeper Angular stuff.
We can discuss and workshop this more if you want.

**Comment by chartjes** [comment]
wontfix
