### ISSUE TITLE
How do we share project.json files?

### ISSUE THREAD

**Issue by pdehaan** [loads/loads-web#66]
I think we have a couple great ideas on the go. This is just a pathetic attempt to consolidate random thoughts...

---

1. Create a dummy GitHub user with a shared username/password where we save all gists. Then we can build some simple "gist browser/database" thing.
  **PROS:**
    - Gists can be loaded and saved to a single place so we can organize them and people can comment on GitHub or wherever.
  
  **CONS:**
    - We can't just create some faceless GitHub org (from github.com/loads) and seemingly host gists there, it has to be tied to an actual user account.
    - Forking a Gist via github.com would move it into the forkers repo.
    - You'd see all the gists. Unless we build some user specific logic in a remote db so you can "favorite" specific gists you care about or maybe hide ones you really dont care about.

2. Gists are owned by people and you can simply load any arbitrary gist (which we sort of have now). We could expand this to use something like localstorage or [localforage](https://github.com/mozilla/localForage) (via [angular-localForage](https://github.com/ocombe/angular-localForage)?) to persist any previously loaded gists, so we can display your previously viewed/loaded gists locally.

  **PROS:**
    - Kind of neat. Doesn't require any DB.
    - You only see gists that you want, and you can hide ones you dont care about anymore.

  **CONS:**
    - You have to know specific Gist ids to search for (but only once).
    - I said "once", but i mean "once per machine" since it is local storage.
    - Clear your local storage, and you'd have to re-search all those gists again.

**Comment by pdehaan** [comment]
Sorry, just a brain dump.
Pros and cons to each. Using localstorage is probably easier, but you may suffer from option paralysis at the thought of a lone "search by gist id" field.

**Comment by pdehaan** [comment]
Related: #58

**Comment by rpappalax** [comment]
Thanks for the brain dump!  Both are really interesting options.  We might able to avoid the cons of [1] with a private repo to which only loads-web has access to with a token, but I'm starting to wonder if we should go with a shared bucket at all.    

To summarize, I think we all like:
A. users can load a <project>.json via a URL from anywhere
      users could thus load them directly from:
      * a project repo 
      * from their own gist on github
      * from someone else's remote gist on github, etc.
B.  users see a cached history of their previous URLs perhaps via localstorage

Adding an additional 'central' bucket for project.json file sharing via gists is a cool idea, but may be offering too many options to the user at the expense of usability. 

What about adding an option for me to 'flag' my own project.json files as public (for others to see)?  Then, when my own cached files come up, I also see the 'public' ones of other people in the same listing.  This way we could avoid entirely using a central bucket and let people host their own gists or whatever.  We'd just need to enforce unique labeling.

**Comment by rpappalax** [comment]
this data will ultimately be stored in DB instead. closing
