### ISSUE TITLE
BACKENDS: alternate brokers for other loadtest tools?

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-web#72]
Our intent in separating the front-end from the loads broker, was to introduce some stability, but this may also allow us to more easily attach other tools we could use for loadtesting (i.e. jmeter, bees, etc.) if we wanted.  once loadsv2 is working, it might be worthwhile considering if there are other tools we might want to leverage.

**Comment by pdehaan** [comment]
![](http://gifrific.com/wp-content/uploads/2012/04/matthew-broderick-oh-my-god.gif)

**Comment by rpappalax** [comment]
something like: http://locust.io/

**Comment by chartjes** [comment]
wontfix
