### ISSUE TITLE
INTEGRATION:  detail view - loadtest run history (datadog/Grafana)

### ISSUE THREAD

**Issue by rpappalax** [loads/loads-web#76]
**SUMMARY**
InfluxDB logs test start and end times, but when we switch to datadog, we'll need to calculate this from within loads-web (instead of on the loads-broke end).

How do we map the loadsv1 concept of a loadtest "run" with a discrete start / end time?

Datadog provides from_ts / to_ts params in URL.  
from_ts = epoch_time(current_time_stamp)

We need a way to link to a detailed view of both active and historical runs by constructing a datadog URL from within loads-web.

Here is a sample datadog URL:
https://app.datadoghq.com/dash/45471/autopush?live=false&is_auto=false&from_ts=1432850061634&to_ts=1432851606096&tile_size=m&tpl_var_env=stage

datadog maps each project name to an id in the URL.  You can leave off the project name "autopush" but you can't leave off the ID "45471" from the URL
TODO:  We'll need to retain a local cache mapping project name to datadog ID or 
get an API key to query these

to_ts = from_ts + run_max_time
TODO: We'll need to log this to our historical test runs.

**ACTIVE RUNS**
https://app.datadoghq.com/dash/45471/autopush?live=false&is_auto=false&from_ts=1432850061634&to_ts=1432851606096&tile_size=m&tpl_var_env=stage

**HISTORICAL RUNS**
https://app.datadoghq.com/dash/45471/autopush?is_auto=false&from_ts=1432850061634&to_ts=1432851606096&tile_size=m&tpl_var_env=stage

**Comment by rpappalax** [comment]
Grafana gets installed with loads-broker.
We can link to Grafana data directly from list page thusly:
(loads-broker) localhost:8080/dashboards/run/<run id hash>/

**Comment by chartjes** [comment]
wontfix
